package ba.posao.controllers;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import ba.posao.beans.Kantoni;
import ba.posao.beans.KantoniRepository;



@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private KantoniRepository kantoniRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewKanton (@RequestParam String naziv) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Kantoni k = new Kantoni();
		k.setNaziv(naziv);
		kantoniRepository.save(k);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Kantoni> getAllKantons() {
		// This returns a JSON or XML with the users
		return kantoniRepository.findAll();
	}
}
