package ba.posao.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import ba.posao.models.Korisnici;
import ba.posao.repositories.KorisnikRepository;


@Controller    // This means that this class is a Controller
@CrossOrigin
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called KantoniRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private KorisnikRepository userRepository;
	
	@GetMapping(path="/all")
	public @ResponseBody String getAllKantoni() {
		// This returns a JSON or XML with the users
		return "uradjeno";
	}
	
	@GetMapping(path="/email")
	public @ResponseBody Korisnici findByEmail(@RequestParam String email) {
		return userRepository.findByEmail(email);
	}
	
	@GetMapping(path="/users")
	public @ResponseBody List<Korisnici> findAll() {
		return userRepository.findAll();
	}
}